config/routes.rb
UTUOnRails::Application.routes.draw do

  resources :lesson_timings
  resources :seminars
  get 'services_generator' => 'services_generator#form', as: 'generate_services_form'
  post 'services_generator' => 'services_generator#generate', as: 'generate_services_generate'

  resources :articles

  resources :holidays

  resources :school_years

  resources :sgroups

  post 'sclasses/change_current' => 'sclasses#change_current'
  resources :sclasses

  resources :class_members

  resources :group_categories

  post 'planned_raking_entries/sort' => 'planned_raking_entries#sort'
  get 'planned_raking_entries/new_planned_rekt' => 'planned_raking_entries#new_planned_rekt', as: 'new_planned_rekt_raking_entry'
  get 'planned_raking_entries/new_already_rekt' => 'planned_raking_entries#new_already_rekt', as: 'new_already_rekt_raking_entry'
  resources :planned_raking_entries, except: [:new, :edit, :update]

  post 'planned_raking_entries/raking_rounds/for_planned_raking_list' => 'raking_rounds#for_planned_raking_list'

  get 'planned_raking_lists/admin_show/:id' => "planned_raking_lists#admin_show", as: "admin_show_planned_raking_lists"
  post 'planned_raking_lists/create_new_round/:id' => "planned_raking_lists#create_new_round", as: "create_new_round_planned_raking_lists"
  resources :planned_raking_lists

  resources :written_exams do
    controller :written_exams do
      get 'transform_to_raking' => :transform_to_raking
    end
  end

  resources :additional_infos

  resources :raking_exams do
    controller :raking_exams do
      get 'transform_to_written' => :transform_to_written
    end
  end

  controller :charts do
    get 'accesses_per_hour_of_day'
    get 'accesses_per_hour_of_last_day'
    get 'accesses_per_day_of_week'
    get 'accesses_per_device'
    get 'accesses_per_user'
    get 'accesses_per_user_type'
    get 'accesses_per_ip'
    get 'accesses_per_last_month_in_days'
    get 'accesses_per_visited_page_type'
  end

  resources :details_accesses

  resources :baka_accounts

  resources :subjects

  resources :timetables do
    get 'fetch_baka' => :fetch_baka
    get 'populate' => :populate
  end

  controller :lessons do
    get 'lessons/dialog_for_timetable', as: :dialog_for_timetable
  end

  resources :day_teachers

  resources :teachers

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'logout' => :destroy
  end

  resources :users

  resources :services

  resources :exams do
    controller :exams do
      get 'transform_to_task' => :transform_to_task
    end
  end

  resources :tasks do
    controller :tasks do
      get 'transform_to_exam' => :transform_to_exam
    end
  end

  resources :events

  root to: 'summary#summary', as: 'utu'

  post 'hiding/hide' => 'hiding#hide'
  post 'hiding/reveal' => 'hiding#reveal'
  get 'hiding/hide' => 'hiding#hide', as: 'hide_item'
  get 'hiding/reveal' => 'hiding#reveal', as: 'reveal_item'

  get 'migrate' => 'summary#migrate'

  get 'welcome_screen' => 'summary#welcome_screen'

  get 'enable_experimental_settings' => 'users#enable_experimental_settings'

  get 'api/pre_data' => 'external_actions#pre_data'
  post 'api/pre_data' => 'external_actions#pre_data'
  get 'api/data' => 'external_actions#data'
  post 'api/data' => 'external_actions#data'
  get 'api/timetables' => 'external_actions#timetables'
  get 'api/only_details' => 'external_actions#only_details'
  post 'api/save' => 'external_actions#save_item'
  post 'api/destroy' => 'external_actions#destroy_item'
  get 'api/administrator_authenticated' => 'external_actions#administrator_logged_in'
  post 'api/hide' => 'external_actions#hide_item'
  post 'api/reveal' => 'external_actions#reveal_item'

  get 'opensearch' => 'external_actions#opensearch'

  get 'analyze' => 'details_accesses#analyze'
  get 'statistics' => 'details_accesses#analyze'
  get 'stats' => 'details_accesses#analyze'

  get 'forgot' => 'users#forgot_password_form'
  get 'forgot_code' => 'users#forgot_password_code'
  post 'forgot' => 'users#forgot_password_send'

  get 'wwe' => 'summary#john_cena'
  get 'subjects_summary' => 'summary#subjects'
  
  get 'vote' => 'day_teachers#new'

  get 'update' => 'summary#update'
  get 'details' => 'summary#details'
  post 'details' => 'summary#post_details'
  get 'search' => 'summary#search'
  
  get 'rozvrh' => 'timetables#summary'
  get 'timetable' => 'timetables#summary'
  
  get 'service_list' => 'summary#service_list'
  
  get 'administration' => 'summary#administration'
  
  get 'register' => 'users#new'
  delete 'destroy_account/:id', to: 'users#self_destroy', as: 'destroy_account'

  get 'show_transform_to_selection_dialog' => 'generic_actions#transform_to_selection_dialog'

end

app/models/services/holiday.rb
class HolidayDateValidator < ActiveModel::Validator
  def validate(record)
    if record.holiday_end < record.holiday_beginning
      record.errors.add(:holiday_end, 'musí být později než začátek prázdnin')
    end
  end
end

class Holiday < ActiveRecord::Base
  belongs_to :school_year

  validates_with HolidayDateValidator

  validates_presence_of :holiday_beginning, :holiday_end, :school_year
end

app/controllers/holidays_controller.rb
class HolidaysController < ApplicationController
  before_action :set_holiday, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_admin, except: [:index, :show]
  before_filter :authenticate, only: [:index, :show]

  # GET /holidays
  # GET /holidays.json
  def index
    @holidays = Holiday.all
  end

  # GET /holidays/1
  # GET /holidays/1.json
  def show
  end

  # GET /holidays/new
  def new
    @holiday = Holiday.new
  end

  # GET /holidays/1/edit
  def edit
  end

  # POST /holidays
  # POST /holidays.json
  def create
    @holiday = Holiday.new(holiday_params)

    respond_to do |format|
      if @holiday.save
        format.html { redirect_to @holiday, notice: 'Holiday was successfully created.' }
        format.json { render :show, status: :created, location: @holiday }
      else
        format.html { render :new }
        format.json { render json: @holiday.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /holidays/1
  # PATCH/PUT /holidays/1.json
  def update
    respond_to do |format|
      if @holiday.update(holiday_params)
        format.html { redirect_to @holiday, notice: 'Holiday was successfully updated.' }
        format.json { render :show, status: :ok, location: @holiday }
      else
        format.html { render :edit }
        format.json { render json: @holiday.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /holidays/1
  # DELETE /holidays/1.json
  def destroy
    @holiday.destroy
    respond_to do |format|
      format.html { redirect_to holidays_url, notice: 'Holiday was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_holiday
      @holiday = Holiday.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def holiday_params
      params.require(:holiday).permit(:holiday_beginning, :holiday_end, :school_year_id, :name)
    end
end

app/views/holidays/_form.html.erb
<%= form_for(@holiday) do |f| %>
    <% if @holiday.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@holiday.errors.count, "error") %> prohibited this holiday from being saved:</h2>

          <ul>
            <% @holiday.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>

    <div class="field">
      <%= f.label :holiday_beginning %><br>
      <%= f.date_select :holiday_beginning %>
    </div>
    <div class="field">
      <%= f.label :holiday_end %><br>
      <%= f.date_select :holiday_end %>
    </div>
    <div class="field">
      <%= f.label :school_year_id %><br>
      <%= f.collection_select(:school_year_id, SchoolYear.order("beginning_year DESC").all, :id, :readable_name) %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/holidays/edit.html.erb
<h1>Editing holiday</h1>

<%= render 'form' %>

<%= link_to 'Show', @holiday %> |
<%= link_to 'Back', holidays_path %>

app/views/holidays/index.html.erb
<h1>Listing holidays</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Holiday beginning</th>
      <th>Holiday end</th>
      <th>School year</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @holidays.each do |holiday| %>
      <tr>
        <td><%= holiday.name %></td>
        <td><%= holiday.holiday_beginning %></td>
        <td><%= holiday.holiday_end %></td>
        <td><%= holiday.school_year.readable_name %></td>
        <td><%= link_to 'Show', holiday %></td>
        <td><%= link_to 'Edit', edit_holiday_path(holiday) %></td>
        <td><%= link_to 'Destroy', holiday, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Holiday', new_holiday_path %>

app/views/holidays/new.html.erb
<h1>New holiday</h1>

<%= render 'form' %>

<%= link_to 'Back', holidays_path %>

app/views/holidays/show.html.erb
<h3><%= @holiday.name %></h3>

<p>
  <strong>Holiday beginning:</strong>
  <%= @holiday.holiday_beginning %>
</p>

<p>
  <strong>Holiday end:</strong>
  <%= @holiday.holiday_end %>
</p>

<p>
  <strong>School year:</strong>
  <%= @holiday.school_year.readable_name %>
</p>

<%= link_to 'Edit', edit_holiday_path(@holiday) %> |
<%= link_to 'Back', holidays_path %>