config/routes.rb
UTUOnRails::Application.routes.draw do

  resources :lesson_timings
  resources :seminars
  get 'services_generator' => 'services_generator#form', as: 'generate_services_form'
  post 'services_generator' => 'services_generator#generate', as: 'generate_services_generate'

  resources :articles

  resources :holidays

  resources :school_years

  resources :sgroups

  post 'sclasses/change_current' => 'sclasses#change_current'
  resources :sclasses

  resources :class_members

  resources :group_categories

  post 'planned_raking_entries/sort' => 'planned_raking_entries#sort'
  get 'planned_raking_entries/new_planned_rekt' => 'planned_raking_entries#new_planned_rekt', as: 'new_planned_rekt_raking_entry'
  get 'planned_raking_entries/new_already_rekt' => 'planned_raking_entries#new_already_rekt', as: 'new_already_rekt_raking_entry'
  resources :planned_raking_entries, except: [:new, :edit, :update]

  post 'planned_raking_entries/raking_rounds/for_planned_raking_list' => 'raking_rounds#for_planned_raking_list'

  get 'planned_raking_lists/admin_show/:id' => "planned_raking_lists#admin_show", as: "admin_show_planned_raking_lists"
  post 'planned_raking_lists/create_new_round/:id' => "planned_raking_lists#create_new_round", as: "create_new_round_planned_raking_lists"
  resources :planned_raking_lists

  resources :written_exams do
    controller :written_exams do
      get 'transform_to_raking' => :transform_to_raking
    end
  end

  resources :additional_infos

  resources :raking_exams do
    controller :raking_exams do
      get 'transform_to_written' => :transform_to_written
    end
  end

  controller :charts do
    get 'accesses_per_hour_of_day'
    get 'accesses_per_hour_of_last_day'
    get 'accesses_per_day_of_week'
    get 'accesses_per_device'
    get 'accesses_per_user'
    get 'accesses_per_user_type'
    get 'accesses_per_ip'
    get 'accesses_per_last_month_in_days'
    get 'accesses_per_visited_page_type'
  end

  resources :details_accesses

  resources :baka_accounts

  resources :subjects

  resources :timetables do
    get 'fetch_baka' => :fetch_baka
    get 'populate' => :populate
  end

  controller :lessons do
    get 'lessons/dialog_for_timetable', as: :dialog_for_timetable
  end

  resources :day_teachers

  resources :teachers

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'logout' => :destroy
  end

  resources :users

  resources :services

  resources :exams do
    controller :exams do
      get 'transform_to_task' => :transform_to_task
    end
  end

  resources :tasks do
    controller :tasks do
      get 'transform_to_exam' => :transform_to_exam
    end
  end

  resources :events

  root to: 'summary#summary', as: 'utu'

  post 'hiding/hide' => 'hiding#hide'
  post 'hiding/reveal' => 'hiding#reveal'
  get 'hiding/hide' => 'hiding#hide', as: 'hide_item'
  get 'hiding/reveal' => 'hiding#reveal', as: 'reveal_item'

  get 'migrate' => 'summary#migrate'

  get 'welcome_screen' => 'summary#welcome_screen'

  get 'enable_experimental_settings' => 'users#enable_experimental_settings'

  get 'api/pre_data' => 'external_actions#pre_data'
  post 'api/pre_data' => 'external_actions#pre_data'
  get 'api/data' => 'external_actions#data'
  post 'api/data' => 'external_actions#data'
  get 'api/timetables' => 'external_actions#timetables'
  get 'api/only_details' => 'external_actions#only_details'
  post 'api/save' => 'external_actions#save_item'
  post 'api/destroy' => 'external_actions#destroy_item'
  get 'api/administrator_authenticated' => 'external_actions#administrator_logged_in'
  post 'api/hide' => 'external_actions#hide_item'
  post 'api/reveal' => 'external_actions#reveal_item'

  get 'opensearch' => 'external_actions#opensearch'

  get 'analyze' => 'details_accesses#analyze'
  get 'statistics' => 'details_accesses#analyze'
  get 'stats' => 'details_accesses#analyze'

  get 'forgot' => 'users#forgot_password_form'
  get 'forgot_code' => 'users#forgot_password_code'
  post 'forgot' => 'users#forgot_password_send'

  get 'wwe' => 'summary#john_cena'
  get 'subjects_summary' => 'summary#subjects'
  
  get 'vote' => 'day_teachers#new'

  get 'update' => 'summary#update'
  get 'details' => 'summary#details'
  post 'details' => 'summary#post_details'
  get 'search' => 'summary#search'
  
  get 'rozvrh' => 'timetables#summary'
  get 'timetable' => 'timetables#summary'
  
  get 'service_list' => 'summary#service_list'
  
  get 'administration' => 'summary#administration'
  
  get 'register' => 'users#new'
  delete 'destroy_account/:id', to: 'users#self_destroy', as: 'destroy_account'

  get 'show_transform_to_selection_dialog' => 'generic_actions#transform_to_selection_dialog'

end

app/models/utu_items/components/teacher.rb
class Teacher < ActiveRecord::Base
  validates :name, presence: {presence: true, message: "nesmí být prázdný"}
  has_many :day_teachers
  has_many :lessons
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_filter :authenticate_admin
  before_action :set_teacher, only: [:show, :edit, :update, :destroy]

  # GET /teachers
  # GET /teachers.json
  def index
    @teachers = Teacher.all
  end

  # GET /teachers/1
  # GET /teachers/1.json
  def show
  end

  # GET /teachers/new
  def new
    @teacher = Teacher.new
  end

  # GET /teachers/1/edit
  def edit
  end

  # POST /teachers
  # POST /teachers.json
  def create
    @teacher = Teacher.new(teacher_params)

    respond_to do |format|
      if @teacher.save
        format.html { redirect_to @teacher, notice: 'Teacher was successfully created.' }
        format.json { render :show, status: :created, location: @teacher }
      else
        format.html { render :new }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teachers/1
  # PATCH/PUT /teachers/1.json
  def update
    respond_to do |format|
      if @teacher.update(teacher_params)
        format.html { redirect_to @teacher, notice: 'Teacher was successfully updated.' }
        format.json { render :show, status: :ok, location: @teacher }
      else
        format.html { render :edit }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1
  # DELETE /teachers/1.json
  def destroy
    @teacher.destroy
    respond_to do |format|
      format.html { redirect_to teachers_url, notice: 'Teacher was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teacher_params
      params.require(:teacher).permit(:name, :description, :abbr)
    end
end

app/views/teachers/_form.html.erb
<%= form_for(@teacher) do |f| %>
  <% if @teacher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
      <% @teacher.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :abbr %><br>
    <%= f.text_field :abbr %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/teachers/edit.html.erb
<h1>Editing teacher</h1>

<%= render 'form' %>

<%= link_to 'Zobrazit', @teacher %> |
<%= link_to 'Back', teachers_path %>

app/views/teachers/index.html.erb
<h1>Listing teachers</h1>

<table>
  <thead>
    <tr>
      <th>Jméno</th>
      <th>Popis</th>
      <th>Zkratka</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @teachers.each do |teacher| %>
      <tr>
        <td><%= teacher.name %></td>
        <td><%= teacher.description %></td>
        <td><%= teacher.abbr %></td>
        <td><%= link_to 'Zobrazit', teacher %></td>
        <td><%= link_to 'Upravit', edit_teacher_path(teacher) %></td>
        <td><%= link_to 'Odstranit', teacher, method: :delete, data: { confirm: 'Jste si jisti?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Teacher', new_teacher_path %>

app/views/teachers/new.html.erb
<h1>New teacher</h1>

<%= render 'form' %>

<%= link_to 'Back', teachers_path %>

app/views/teachers/show.html.erb
<p>
  <strong>Jméno:</strong>
  <%= @teacher.name %>
</p>

<p>
  <strong>Popis:</strong>
  <%= @teacher.description %>
</p>

<p>
  <strong>Zkratka:</strong>
  <%= @teacher.abbr %>
</p>


<%= link_to 'Upravit', edit_teacher_path(@teacher) %> |
<%= link_to 'Back', teachers_path %>