config/routes.rb
UTUOnRails::Application.routes.draw do

  resources :lesson_timings
  resources :seminars
  get 'services_generator' => 'services_generator#form', as: 'generate_services_form'
  post 'services_generator' => 'services_generator#generate', as: 'generate_services_generate'

  resources :articles

  resources :holidays

  resources :school_years

  resources :sgroups

  post 'sclasses/change_current' => 'sclasses#change_current'
  resources :sclasses

  resources :class_members

  resources :group_categories

  post 'planned_raking_entries/sort' => 'planned_raking_entries#sort'
  get 'planned_raking_entries/new_planned_rekt' => 'planned_raking_entries#new_planned_rekt', as: 'new_planned_rekt_raking_entry'
  get 'planned_raking_entries/new_already_rekt' => 'planned_raking_entries#new_already_rekt', as: 'new_already_rekt_raking_entry'
  resources :planned_raking_entries, except: [:new, :edit, :update]

  post 'planned_raking_entries/raking_rounds/for_planned_raking_list' => 'raking_rounds#for_planned_raking_list'

  get 'planned_raking_lists/admin_show/:id' => "planned_raking_lists#admin_show", as: "admin_show_planned_raking_lists"
  post 'planned_raking_lists/create_new_round/:id' => "planned_raking_lists#create_new_round", as: "create_new_round_planned_raking_lists"
  resources :planned_raking_lists

  resources :written_exams do
    controller :written_exams do
      get 'transform_to_raking' => :transform_to_raking
    end
  end

  resources :additional_infos

  resources :raking_exams do
    controller :raking_exams do
      get 'transform_to_written' => :transform_to_written
    end
  end

  controller :charts do
    get 'accesses_per_hour_of_day'
    get 'accesses_per_hour_of_last_day'
    get 'accesses_per_day_of_week'
    get 'accesses_per_device'
    get 'accesses_per_user'
    get 'accesses_per_user_type'
    get 'accesses_per_ip'
    get 'accesses_per_last_month_in_days'
    get 'accesses_per_visited_page_type'
  end

  resources :details_accesses

  resources :baka_accounts

  resources :subjects

  resources :timetables do
    get 'fetch_baka' => :fetch_baka
    get 'populate' => :populate
  end

  controller :lessons do
    get 'lessons/dialog_for_timetable', as: :dialog_for_timetable
  end

  resources :day_teachers

  resources :teachers

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'logout' => :destroy
  end

  resources :users

  resources :services

  resources :exams do
    controller :exams do
      get 'transform_to_task' => :transform_to_task
    end
  end

  resources :tasks do
    controller :tasks do
      get 'transform_to_exam' => :transform_to_exam
    end
  end

  resources :events

  root to: 'summary#summary', as: 'utu'

  post 'hiding/hide' => 'hiding#hide'
  post 'hiding/reveal' => 'hiding#reveal'
  get 'hiding/hide' => 'hiding#hide', as: 'hide_item'
  get 'hiding/reveal' => 'hiding#reveal', as: 'reveal_item'

  get 'migrate' => 'summary#migrate'

  get 'welcome_screen' => 'summary#welcome_screen'

  get 'enable_experimental_settings' => 'users#enable_experimental_settings'

  get 'api/pre_data' => 'external_actions#pre_data'
  post 'api/pre_data' => 'external_actions#pre_data'
  get 'api/data' => 'external_actions#data'
  post 'api/data' => 'external_actions#data'
  get 'api/timetables' => 'external_actions#timetables'
  get 'api/only_details' => 'external_actions#only_details'
  post 'api/save' => 'external_actions#save_item'
  post 'api/destroy' => 'external_actions#destroy_item'
  get 'api/administrator_authenticated' => 'external_actions#administrator_logged_in'
  post 'api/hide' => 'external_actions#hide_item'
  post 'api/reveal' => 'external_actions#reveal_item'

  get 'opensearch' => 'external_actions#opensearch'

  get 'analyze' => 'details_accesses#analyze'
  get 'statistics' => 'details_accesses#analyze'
  get 'stats' => 'details_accesses#analyze'

  get 'forgot' => 'users#forgot_password_form'
  get 'forgot_code' => 'users#forgot_password_code'
  post 'forgot' => 'users#forgot_password_send'

  get 'wwe' => 'summary#john_cena'
  get 'subjects_summary' => 'summary#subjects'
  
  get 'vote' => 'day_teachers#new'

  get 'update' => 'summary#update'
  get 'details' => 'summary#details'
  post 'details' => 'summary#post_details'
  get 'search' => 'summary#search'
  
  get 'rozvrh' => 'timetables#summary'
  get 'timetable' => 'timetables#summary'
  
  get 'service_list' => 'summary#service_list'
  
  get 'administration' => 'summary#administration'
  
  get 'register' => 'users#new'
  delete 'destroy_account/:id', to: 'users#self_destroy', as: 'destroy_account'

  get 'show_transform_to_selection_dialog' => 'generic_actions#transform_to_selection_dialog'

end

app/controllers/sclasses_controller.rb
class SclassesController < ApplicationController
  before_action :set_sclass, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_admin, except: [:change_current]
  skip_before_filter :current_class_check, only: [:change_current]

  # GET /sclasses
  # GET /sclasses.json
  def index
    @sclasses = Sclass.all
  end

  # GET /sclasses/1
  # GET /sclasses/1.json
  def show
  end

  # GET /sclasses/new
  def new
    @sclass = Sclass.new
  end

  # GET /sclasses/1/edit
  def edit
  end

  # POST /sclasses
  # POST /sclasses.json
  def create
    @sclass = Sclass.new(sclass_params)

    respond_to do |format|
      if @sclass.save
        format.html { redirect_to @sclass, notice: 'Sclass was successfully created.' }
        format.json { render :show, status: :created, location: @sclass }
      else
        format.html { render :new }
        format.json { render json: @sclass.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sclasses/1
  # PATCH/PUT /sclasses/1.json
  def update
    respond_to do |format|
      if @sclass.update(sclass_params)
        format.html { redirect_to @sclass, notice: 'Sclass was successfully updated.' }
        format.json { render :show, status: :ok, location: @sclass }
      else
        format.html { render :edit }
        format.json { render json: @sclass.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sclasses/1
  # DELETE /sclasses/1.json
  def destroy
    @sclass.destroy
    respond_to do |format|
      format.html { redirect_to sclasses_url, notice: 'Sclass was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def change_current
    session[:sclass_id] = params[:sclass_id]
    cookies.permanent[:sclass_id] = params[:sclass_id]
    render 'sclasses/current_class/current_class_changed'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sclass
      @sclass = Sclass.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sclass_params
      params.require(:sclass).permit(:name, :default_timetable_id, default_subscribed_subject_ids:[])
    end
end

app/views/sclasses/_form.html.erb
<%= form_for(@sclass) do |f| %>
    <% if @sclass.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@sclass.errors.count, "error") %> prohibited this sclass from being saved:</h2>

          <ul>
            <% @sclass.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :default_timetable_id %><br>
      <%= f.collection_select :default_timetable_id, Timetable.all, :id, :full_name %>
    </div>
    <div class="field">
      <%= f.label :default_subscribed_subject_ids %><br>
      <%= f.collection_check_boxes :default_subscribed_subject_ids, Subject.all, :id, :name %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/sclasses/edit.html.erb
<h1>Editing sclass</h1>

<%= render 'form' %>

<%= link_to 'Show', @sclass %> |
<%= link_to 'Back', sclasses_path %>

app/views/sclasses/index.html.erb
<h1>Listing sclasses</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sclasses.each do |sclass| %>
      <tr>
        <td><%= sclass.name %></td>
        <td><%= link_to 'Show', sclass %></td>
        <td><%= link_to 'Edit', edit_sclass_path(sclass) %></td>
        <td><%= link_to 'Destroy', sclass, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sclass', new_sclass_path %>

app/views/sclasses/new.html.erb
<h1>New sclass</h1>

<%= render 'form' %>

<%= link_to 'Back', sclasses_path %>

app/views/sclasses/services_report.html.erb
<%# TODO implement rendering classmembers with services %>
<% @class_members.each do |reported| %>
    <%= reported.first_mate.full_name %> <%= reported.second_mate.full_name %> (<%= l reported.service_start %> - <%= l reported.service_end %>)
    <br>
<% end %>

app/views/sclasses/show.html.erb
<h3><%= @sclass.name %></h3>
<div id="sclass_show_user_form">
  <h4>Nový uživatel</h4>
  <%= form_for(ClassMember.new(sclass_id: @sclass.id), remote: true) do |f| %>
      <%= f.hidden_field :sclass_id %>
      <div class="field">
        <%= f.label :first_name, 'Jméno' %>
        <%= f.text_field :first_name %>
        <%= f.text_field :last_name %>
      </div>
      <div class="field">
        <%= label_tag :group, 'Skupiny' %><br>
        <% GroupCategory.all.each do |category| %>
            <strong><%= category.name %></strong>
            <% category.sgroups.each do |sgroup| %>
                <%= radio_button_tag "sgroups[#{category.id}]", sgroup.id %>
                <%= label_tag "sgroups[#{category.id}]", sgroup.name %>
            <% end %>
            <br>
        <% end %>
      </div>
      <div class="field">
        <%= f.submit "Uložit" %>
      </div>
  <% end %>
</div>
<p>
  <strong>Default timetable:</strong>
  <%= @sclass.default_timetable.full_name %>
</p>
<table>
  <thead>
  <tr>
    <th>Jméno</th>
    <th>Skupiny</th>
    <th>Služeb v tomto školním roce</th>
    <th>Uživatel?</th>
    <th></th>
  </tr>
  </thead>
  <tbody id="sclass_show_users_tbody">
  <% @sclass.class_members.order(:last_name).each do |member| %>
      <%= render partial: "class_members/sclass_show/table_tr_for_sclass_show", locals: { class_member: member } %>
  <% end %>
  </tbody>
</table>
<br>
<table>
  <thead>
  <tr>
    <th>Jméno rozvrhu</th>
    <th>Podporované skupiny</th>
  </tr>
  </thead>
  <tbody>
  <% @sclass.timetables.each do |timetable| %>
      <tr>
        <td><%= timetable.name %></td>
        <td><%= timetable.sgroups.pluck(:name).to_sentence %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<%= link_to 'Edit', edit_sclass_path(@sclass) %> |
<%= link_to 'Back', sclasses_path %>