config/routes.rb
UTUOnRails::Application.routes.draw do

  resources :lesson_timings
  resources :seminars
  get 'services_generator' => 'services_generator#form', as: 'generate_services_form'
  post 'services_generator' => 'services_generator#generate', as: 'generate_services_generate'

  resources :articles

  resources :holidays

  resources :school_years

  resources :sgroups

  post 'sclasses/change_current' => 'sclasses#change_current'
  resources :sclasses

  resources :class_members

  resources :group_categories

  post 'planned_raking_entries/sort' => 'planned_raking_entries#sort'
  get 'planned_raking_entries/new_planned_rekt' => 'planned_raking_entries#new_planned_rekt', as: 'new_planned_rekt_raking_entry'
  get 'planned_raking_entries/new_already_rekt' => 'planned_raking_entries#new_already_rekt', as: 'new_already_rekt_raking_entry'
  resources :planned_raking_entries, except: [:new, :edit, :update]

  post 'planned_raking_entries/raking_rounds/for_planned_raking_list' => 'raking_rounds#for_planned_raking_list'

  get 'planned_raking_lists/admin_show/:id' => "planned_raking_lists#admin_show", as: "admin_show_planned_raking_lists"
  post 'planned_raking_lists/create_new_round/:id' => "planned_raking_lists#create_new_round", as: "create_new_round_planned_raking_lists"
  resources :planned_raking_lists

  resources :written_exams do
    controller :written_exams do
      get 'transform_to_raking' => :transform_to_raking
    end
  end

  resources :additional_infos

  resources :raking_exams do
    controller :raking_exams do
      get 'transform_to_written' => :transform_to_written
    end
  end

  controller :charts do
    get 'accesses_per_hour_of_day'
    get 'accesses_per_hour_of_last_day'
    get 'accesses_per_day_of_week'
    get 'accesses_per_device'
    get 'accesses_per_user'
    get 'accesses_per_user_type'
    get 'accesses_per_ip'
    get 'accesses_per_last_month_in_days'
    get 'accesses_per_visited_page_type'
  end

  resources :details_accesses

  resources :baka_accounts

  resources :subjects

  resources :timetables do
    get 'fetch_baka' => :fetch_baka
    get 'populate' => :populate
  end

  controller :lessons do
    get 'lessons/dialog_for_timetable', as: :dialog_for_timetable
  end

  resources :day_teachers

  resources :teachers

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'logout' => :destroy
  end

  resources :users

  resources :services

  resources :exams do
    controller :exams do
      get 'transform_to_task' => :transform_to_task
    end
  end

  resources :tasks do
    controller :tasks do
      get 'transform_to_exam' => :transform_to_exam
    end
  end

  resources :events

  root to: 'summary#summary', as: 'utu'

  post 'hiding/hide' => 'hiding#hide'
  post 'hiding/reveal' => 'hiding#reveal'
  get 'hiding/hide' => 'hiding#hide', as: 'hide_item'
  get 'hiding/reveal' => 'hiding#reveal', as: 'reveal_item'

  get 'migrate' => 'summary#migrate'

  get 'welcome_screen' => 'summary#welcome_screen'

  get 'enable_experimental_settings' => 'users#enable_experimental_settings'

  get 'api/pre_data' => 'external_actions#pre_data'
  post 'api/pre_data' => 'external_actions#pre_data'
  get 'api/data' => 'external_actions#data'
  post 'api/data' => 'external_actions#data'
  get 'api/timetables' => 'external_actions#timetables'
  get 'api/only_details' => 'external_actions#only_details'
  post 'api/save' => 'external_actions#save_item'
  post 'api/destroy' => 'external_actions#destroy_item'
  get 'api/administrator_authenticated' => 'external_actions#administrator_logged_in'
  post 'api/hide' => 'external_actions#hide_item'
  post 'api/reveal' => 'external_actions#reveal_item'

  get 'opensearch' => 'external_actions#opensearch'

  get 'analyze' => 'details_accesses#analyze'
  get 'statistics' => 'details_accesses#analyze'
  get 'stats' => 'details_accesses#analyze'

  get 'forgot' => 'users#forgot_password_form'
  get 'forgot_code' => 'users#forgot_password_code'
  post 'forgot' => 'users#forgot_password_send'

  get 'wwe' => 'summary#john_cena'
  get 'subjects_summary' => 'summary#subjects'
  
  get 'vote' => 'day_teachers#new'

  get 'update' => 'summary#update'
  get 'details' => 'summary#details'
  post 'details' => 'summary#post_details'
  get 'search' => 'summary#search'
  
  get 'rozvrh' => 'timetables#summary'
  get 'timetable' => 'timetables#summary'
  
  get 'service_list' => 'summary#service_list'
  
  get 'administration' => 'summary#administration'
  
  get 'register' => 'users#new'
  delete 'destroy_account/:id', to: 'users#self_destroy', as: 'destroy_account'

  get 'show_transform_to_selection_dialog' => 'generic_actions#transform_to_selection_dialog'

end

app/controllers/summary_controller.rb
require "net/http"
require "uri"
require "mechanize"
require "nokogiri"

class SummaryController < ApplicationController
  skip_before_filter :verify_authenticity_token, :only => [:post_details]
  skip_before_filter :current_class_check, only: [:welcome_screen, :update]
  before_filter :authenticate_admin, only: [:refresh, :migrate, :temp]
  before_filter :authenticate, only: :subjects

  def summary
    @data = {}
    @data[:service] = {}

    @data[:service][:current] = Service.current
    @data[:articles] = Article.where(published: true).for_class(current_class).order("published_on DESC").limit(3)

    if logged_in?
      @data[:service][:user] = Service.in_future.where("first_mate_id = :class_member OR second_mate_id = :class_member", {class_member: current_user.class_member_id}).first
    end

    DetailsAccess.log_new(current_user, request.remote_ip, request.env['HTTP_USER_AGENT'], 'summary')
  end

  def search
    search_parameters = params[:query]
    sclass = current_class
    @data = {}
    @data[:query] = search_parameters
    @data[:items] = Event.for_class(sclass).order(:event_start).like(search_parameters) + Exam.for_class(sclass).order(:date).like(search_parameters) + Task.for_class(sclass).order(:date).like(search_parameters)
  end

  def post_details
    from = Date.parse(params[:from])
    to = Date.parse(params[:to])
    @events = Event.order(:event_start).between_dates(from, to)
    @exams = Exam.order(:date).for_group(params[:group]).between_dates(from, to)
    @tasks = Task.order(:date).for_group(params[:group]).between_dates(from, to)
    if group != 0
      @exams = @exams.for_group(params[:group])
      @tasks = @tasks.for_group(params[:group])
    end

    DetailsAccess.log_new(current_user, request.remote_ip, request.env['HTTP_USER_AGENT'], 'details')

    render 'details.xml'
  end

  def details
    #from = Date.new(params[:range][:"from(1i)"].to_i, params[:range][:"from(2i)"].to_i, params[:range][:"from(3i)"].to_i)
    #to = Date.new(params[:range][:"to(1i)"].to_i, params[:range][:"to(2i)"].to_i, params[:range][:"to(3i)"].to_i)
    @data = {}

    sclass = current_class
    if logged_in?
      user = current_user

      @data[:events] = Event.order(:event_start).in_future.for_groups(user.sgroups).for_class(sclass) + Article.order("published_on DESC").where(published: true).where(show_in_details: true).where("show_in_details_until > :today", {today: Time.now})
      @data[:exams] = Exam.order(:date).in_future.for_groups(user.sgroups).for_class(sclass).filter_out_todays_after(12)
      @data[:tasks] = Task.order(:date).in_future.for_groups(user.sgroups).for_class(sclass).filter_out_todays_after(12)
      puts Event.all.pluck(:sgroup_id)
    else
      if request.format.symbol == :xml
        # you are deprecated
      else
        @data[:events] = Event.all.order(:event_start).in_future.for_class(sclass)
        @data[:exams] = Exam.order(:date).in_future.for_class(sclass).filter_out_todays_after(12)
        @data[:tasks] = Task.order(:date).in_future.for_class(sclass).filter_out_todays_after(12)
      end
    end

    DetailsAccess.log_new(current_user, request.remote_ip, request.env['HTTP_USER_AGENT'], 'details')

    respond_to do |format|
      format.html
    end
  end

  def service_list
    @services = Service.order(:service_start).in_future
  end

  def subjects
    @subjects = Subject.all
  end

  def administration

  end

  def john_cena

  end

  def update
    if Time.now.hour > 17 && Time.now.hour < 18
      # mark todays tasks and exams as in_past
      SchoolDay.where(date: Date.today).find_each do |day|
        day.lessons.find_each do |lesson|
          lesson.exams.find_each do |exam|
            exam.passed = true
            exam.save!
          end
          lesson.tasks.find_each do |task|
            task.passed = true
            task.save!
          end
        end
      end
    end

    # delete old records
    SchoolDay.destroy_all
    timetables = Timetable.all
    timetables.each do |timetable|
      timetable.get_timetable
    end
    render nothing: true
  end

  def welcome_screen
    render '_unsortables/welcome_screen', layout: false
  end

  def migrate
    # raking lists (add sclass_id)
    # raking entries (migrate from name to class_member_id)
    # users (migrate from name to class_member_id)
    # users (migrate from group to groups-and-belongings-and-stuff)
    # utu_items (add sgroup_id, add sclass_id)
    # planned_raking_entries (wipe)
  end

  private

  def drop_todays_after(items, hour)
    if items
      if Time.now >= (Date.today + hour.hours)
        items.drop_while { |e| e.date == Date.today }
      else
        return items
      end
    end
  end

  def drop_hidden(items)
    items.drop_while { |e| e.is_done? }
  end
end

app/views/summary/administration.html.erb
<h1>Nastavení</h1>
<% set_title 'Nastavení' %>
<%= select_tag(:main_sclass_selector, options_from_collection_for_select(Sclass.all, :id, :name, current_class.id), class: 'form-control') if !logged_in? %>
<% if logged_in? %>
    <%= render partial: "users/settings", locals: {user: current_user} %>
<% else %>
    <p>Pro používání této sekce se musíte <%= link_to 'přihlásit', login_path %>
      nebo <%= link_to 'zaregistrovat', register_path %></p>
<% end %>
<h3>Vyhledávání</h3>
<div id="search_box">
  <%= form_tag search_path, method: :get do %>
      <%= search_field_tag :query, '', class: 'form-control search_field' %>
      <%= submit_tag 'Hledat', class: 'btn btn-default' %>
  <% end %>
</div>
<% if admin_logged_in? %>
    <%= render "administration_menu" %><br/>
<% end %>
<% if Rails.env.development? %>
    <%= console %>
<% end %>
<!---
<h3>Kontakt</h3>
<p>Našli jste chybu nebo máte jakýkoliv jiný problém? Obraťte se na naši podporu.</p>
<%= mail_to "cendrb@gmail.com", 'Odeslat email', encode: "javascript" %><br />
---->

app/views/summary/details.html.erb
<% set_title 'Podrobnosti' %>
<div class="details_container container-fluid">
  <div id="details_row row">
    <div class="details_col col-sm-4 col-xs-12">
      <div class="details_block">
        <% if admin_logged_in? %>
            <h1><%= link_to "Události", events_path %></h1>
        <% else %>
            <h1>Události</h1>
        <% end %>
        <% @data[:events].each do |e| %>
            <%= render partial: "_generic_utu_partials/show", locals: {item: e} %>
            <%= render 'line' unless e == @data[:events].last %>
        <% end %>
      </div>
    </div>
    <div class="details_col col-sm-4 col-xs-12">
      <div id="middle_detail_block" class="details_block">
        <% if admin_logged_in? %>
            <h1><%= link_to "Úkoly", tasks_path %></h1>
        <% else %>
            <h1>Úkoly</h1>
        <% end %>
        <% @data[:tasks].each do |e| %>
            <%= render partial: "_generic_utu_partials/show", locals: {item: e} %>
            <%= render 'line' unless e == @data[:tasks].last %>
        <% end %>
      </div>
    </div>
    <div class="details_col col-sm-4 col-xs-12">
      <div class="details_block">
        <% if admin_logged_in? %>
            <h1><%= link_to "Testy", written_exams_path %></h1>
        <% else %>
            <h1>Testy</h1>
        <% end %>
        <% @data[:exams].each do |e| %>
            <%= render partial: "_generic_utu_partials/show", locals: {item: e} %>
            <%= render 'line' unless e == @data[:exams].last %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/summary/index.html.erb
<h1>Vše je "dočasné" a nikdo neví, jestli něco ze stávajícího obsahu vůbec zbyde!</h1>
<div class="events">
    <h2>Události</h2>
    <% @events.each do |event| %>
    <div class="line_item">
        <h3><%= event.title %></h3>
        <%= sanitize(event.description) %>
        <br />
        <%= event.location %>
    </div>
    <% end %>
</div>
</div>

app/views/summary/john_cena.html.erb
<script src="//cdn.jsdelivr.net/phaser/2.4.4/phaser.min.js"></script>
<script>
  var game = new Phaser.Game(800, 600, Phaser.AUTO, 'material_body_content', {
    preload: preload,
    create: create,
    update: update
  });

  function preload() {
    game.load.image('johncena', 'assets/john-cena-face.png');
    game.load.image('ground', 'assets/ground.png');
  }

  var obstacles;
  var player;
  function create() {
    game.physics.startSystem(Phaser.Physics.ARCADE); // enable ingame physics

    obstacles = game.add.group(); // add game_group
    obstacles.enableBody = true; // enable physics

    var ground = obstacles.create(0, game.world.height - 64, 'ground');
    ground.body.immovable = true;

    player = game.add.sprite(64, game.world.height - 150, 'johncena');
    game.physics.arcade.enable(player);
    player.body.bounce.y = 0.2;
    player.body.gravity.y = 300;
    player.body.collideWorldBounds = true;
    player.scale.setTo(0.4, 0.4);
  }

  function update() {
    game.physics.arcade.collide(player, obstacles);
  }
</script>

app/views/summary/migrate.html.erb
<H1>MIGRATION SUCCESSFUL</H1>

app/views/summary/refresh_baka.html.erb
<%= @fap %>

app/views/summary/search.html.erb
<% set_title 'Výsledky hledání' %>
<div class="details_container container-fluid">
  <div id="details_row row">
    <div class="details_col col-sm-12">
      <div class="details_block">
        <h1>Výsledky hledání <%= @data[:query] %></h1>
        <% @data[:items].each do |e| %>
            <%= render partial: "_generic_utu_partials/show", locals: {item: e} %>
            <%= render 'line' unless e == @data[:items].last %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/summary/service_list.html.erb
<div id="services">
    <h1>Služby</h1>
    <% @services.each do |service| %>
    <div class="service">
        <strong><%= service.first_name %> a <%= service.second_name %></strong>
        <br />
        <strong>Od:</strong> <%= l service.service_start %>
        <br />
        <strong>Do:</strong> <%= l service.service_end %>
    </div>
    <% end %>
</div>

app/views/summary/settings.html.erb
<h2>Nastavení</h2>

<%= form_tag do %>
<%= select_tag "PENIS" %>
<% end %>

<!-- INSERT USER RENDERING! -->

app/views/summary/subjects.html.erb
<h1>Statistika předmětů</h1>
<table id="subjects_stats">
    <tr>
        <th class="subject_header">Předmět</th>
        <th class="subject_header">Další test</th>
        <th class="subject_header">Poslední test</th>
        <th class="subject_header">Počet testů</th>
        <th class="subject_header">Počet úkolů</th>
    </tr>
    <% @subjects.each do |subject| %>
        <%= render subject %>
    <% end %>
</table>

app/views/summary/summary.html.erb
<h1>Přehled</h1>
<% set_title 'Přehled' %>

<div class="summary_section">
  <h2>Úvod</h2>
  <p>Vítejte na webové verzi Utu. Veškerá data jsou uložena pouze ve zdejší databázi a i desktopová aplikace tento web
    využívá. Tato stránka "běží na" frameworku <%= link_to 'Ruby on Rails', 'http://rubyonrails.org/' %>, který mimo
    jiné
    využívá třeba Twitter.
  </p>
</div>

<div class="summary_section">
  <h2>Služba</h2>
  <% if @data[:service][:current] %>
      <p>Službu na aktuální týden má <strong><%= @data[:service][:current].first_mate.full_name %></strong> a
        <strong><%= @data[:service][:current].second_mate.full_name %></strong>
  <% else %>
      <p>Na aktuální týden nebyla určena žádná služba.
  <% end %>
  <br/>
  Soupis veškerých služeb najdete <%= link_to "zde", :services %></p>

  <% if logged_in? %>
      <% if @data[:service][:user] %>
          <p>
            Vaše období služby začíná <strong><%= l @data[:service][:user].service_start %></strong> a končí
            <strong><%= l @data[:service][:user].service_end %></strong>

            <br/>
            <%= link_to 'Více informací o vaší službě', @data[:service][:user] %>
          </p>
      <% end %>

  <% else %>
      <h5>Pro zpřístupnění následujících funkcí se prosím <%= link_to 'přihlašte', login_path %>
        nebo <%= link_to 'zaregistrujte', register_path %>.</h5>
      <ul>
        <li>
          personalizované zobrazení služby
        </li>
        <li>
          filtrované zobrazení položek
        </li>
        <li>
          možnost skrytí libovolné položky
        </li>
        <li>
          automatické zobrazení rozvrhu pro vaší skupinu
        </li>
        <li>
          a postupem času i mnoho dalšího ;)
        </li>
      </ul>
  <% end %>
</div>

<% if @data[:articles] && @data[:articles].count > 0 %>
    <div class="summary_section">
      <% if admin_logged_in? %>
          <div class="float_right_actions">
            <%= link_to mi.add.md_36, new_article_path %>
            <%= link_to mi.view_list.md_36, articles_path %>
          </div>
      <% end %>
      <h2>Poslední zprávy</h2>
      <% @data[:articles].each do |article| %>
          <%= render partial: "articles/article", locals: {article: article, hide_published: true} %>
      <% end %>
    </div>
<% end %>
<!---
<div class="summary_section">
  <h2>Manuální zobrazení podrobností z libovolného období</h2>
  <%= form_tag(details_path, method: 'get') do %>
      <div class="field">
        <%= label_tag :from, 'Od:' %>
    <%= date_select :range, :from, order: [:day, :month, :year] %>
      </div>
      <div class="field">
        <%= label_tag :to, 'Do:' %>
    <%= date_select :range, :to, order: [:day, :month, :year] %>
      </div>
      <div class="field">
        <%= label_tag :group, 'Skupina:' %>
    <%= number_field_tag :group, '1' %>
      </div>
      <div class="field">
        <%= submit_tag 'Zobrazit' %>
      </div>
  <% end %>
</div>
--->